import * as React from 'react';
import {
  Badge,
  Button,
  ExpandableSection,
  Flex,
  FlexItem,
  Label,
  SearchInput,
  Text,
  TextContent,
  TextVariants,
} from '@patternfly/react-core';
import { DownloadIcon } from '@patternfly/react-icons';
import { CLUSTER_WIDE_CATEGORIES, OpenShiftMetric } from '../../../data/openshiftMetricsConfig';
import { downloadAsFile } from '../../../utils/downloadFile';

const matchesSearch = (metric: OpenShiftMetric, lower: string): boolean =>
  metric.key.toLowerCase().includes(lower) ||
  metric.label.toLowerCase().includes(lower) ||
  metric.description.toLowerCase().includes(lower);

interface OpenShiftMetricsSettingsTabProps {
  downloadRef?: React.MutableRefObject<(() => void) | null>;
  hideHeader?: boolean;
}

export const OpenShiftMetricsSettingsTab: React.FC<OpenShiftMetricsSettingsTabProps> = ({ downloadRef, hideHeader }) => {
  const [searchTerm, setSearchTerm] = React.useState('');
  const [debouncedSearch, setDebouncedSearch] = React.useState('');
  const [expandedSections, setExpandedSections] = React.useState<Record<string, boolean>>({});

  React.useEffect(() => {
    const timer = setTimeout(() => setDebouncedSearch(searchTerm), 200);
    return () => clearTimeout(timer);
  }, [searchTerm]);

  const handleToggle = React.useCallback((sectionId: string, expanded: boolean) => {
    setExpandedSections(prev => ({ ...prev, [sectionId]: expanded }));
  }, []);

  const lower = debouncedSearch.toLowerCase();

  const filteredCategories = React.useMemo(() => {
    if (!debouncedSearch) return Object.entries(CLUSTER_WIDE_CATEGORIES);
    return Object.entries(CLUSTER_WIDE_CATEGORIES).filter(([name, cat]) => {
      if (name.toLowerCase().includes(lower) || cat.description.toLowerCase().includes(lower)) return true;
      return cat.metrics.some(m => matchesSearch(m, lower));
    });
  }, [debouncedSearch, lower]);

  const getFilteredMetrics = (metrics: OpenShiftMetric[]): OpenShiftMetric[] => {
    if (!debouncedSearch) return metrics;
    return metrics.filter(m => matchesSearch(m, lower));
  };

  const totalMetrics = Object.values(CLUSTER_WIDE_CATEGORIES).reduce((sum, cat) => sum + cat.metrics.length, 0);

  const handleDownload = React.useCallback(() => {
    const timestamp = new Date().toISOString();
    const categoryEntries = Object.entries(CLUSTER_WIDE_CATEGORIES);

    let md = `# OpenShift Metrics Reference\n\n`;
    md += `## Overview\n\n`;
    md += `This document organizes **${totalMetrics} OpenShift metrics** into **${categoryEntries.length} categories** used in the OpenShift Metrics page.\n\n`;
    md += `> Generated: ${timestamp}\n\n`;

    // Category summary table
    md += `## Category Summary\n\n`;
    md += `| Category | Metrics |\n`;
    md += `|----------|---------|\n`;
    categoryEntries.forEach(([name, cat]) => {
      md += `| ${name} | ${cat.metrics.length} |\n`;
    });
    md += `| **TOTAL** | **${totalMetrics}** |\n\n`;
    md += `---\n\n`;

    // Detailed categories with collapsible sections
    md += `## Detailed Categories\n\n`;
    categoryEntries.forEach(([name, cat]) => {
      md += `### ${name}\n\n`;
      md += `**Description:** ${cat.description}\n\n`;
      md += `**Metrics:** ${cat.metrics.length}\n\n`;
      md += `<details>\n<summary><b>📋 View all ${cat.metrics.length} metrics</b></summary>\n\n`;
      md += `| # | Metric | Label | Unit |\n`;
      md += `|---|--------|-------|------|\n`;
      cat.metrics.forEach((m, i) => {
        md += `| ${i + 1} | \`${m.key}\` | ${m.label} | ${m.unit || '-'} |\n`;
      });
      md += `\n</details>\n\n`;
    });

    md += `---\n*Generated by OpenShift AI Observability Plugin*\n`;
    downloadAsFile(md, `openshift-metrics-reference-${Date.now()}.md`);
  }, [totalMetrics]);

  // Register download handler on the ref so the parent wrapper can trigger it
  React.useEffect(() => {
    if (downloadRef) {
      downloadRef.current = handleDownload;
    }
    return () => {
      if (downloadRef) {
        downloadRef.current = null;
      }
    };
  }, [downloadRef, handleDownload]);

  return (
    <div style={{ marginTop: '16px' }}>
      {!hideHeader && (
        <Flex justifyContent={{ default: 'justifyContentSpaceBetween' }} alignItems={{ default: 'alignItemsCenter' }} style={{ marginBottom: '16px' }}>
          <FlexItem>
            <TextContent>
              <Text component={TextVariants.h4}>OpenShift Metrics</Text>
              <Text component={TextVariants.small} style={{ color: 'var(--pf-v5-global--Color--200)' }}>
                {totalMetrics} metrics across {Object.keys(CLUSTER_WIDE_CATEGORIES).length} categories used in the OpenShift Metrics page.
              </Text>
            </TextContent>
          </FlexItem>
          <FlexItem>
            <Button
              variant="secondary"
              icon={<DownloadIcon />}
              onClick={handleDownload}
              aria-label="Download OpenShift metrics as markdown"
            >
              Download
            </Button>
          </FlexItem>
        </Flex>
      )}

      <SearchInput
        placeholder="Search OpenShift metrics..."
        value={searchTerm}
        onChange={(_evt, value) => setSearchTerm(value)}
        onClear={() => setSearchTerm('')}
        style={{ marginBottom: '16px' }}
        aria-label="Search OpenShift metrics"
      />

      {filteredCategories.length === 0 ? (
        <TextContent>
          <Text component={TextVariants.p} style={{ color: 'var(--pf-v5-global--Color--200)', textAlign: 'center', padding: '20px' }}>
            No categories or metrics match the search.
          </Text>
        </TextContent>
      ) : (
        filteredCategories.map(([name, cat]) => {
          const metrics = getFilteredMetrics(cat.metrics);
          if (debouncedSearch && metrics.length === 0 && !name.toLowerCase().includes(lower) && !cat.description.toLowerCase().includes(lower)) {
            return null;
          }
          const displayMetrics = metrics.length > 0 ? metrics : cat.metrics;
          const isExpanded = expandedSections[name] ?? false;

          return (
            <ExpandableSection
              key={name}
              isExpanded={isExpanded}
              onToggle={(_evt, expanded) => handleToggle(name, expanded)}
              toggleContent={
                <Flex alignItems={{ default: 'alignItemsCenter' }}>
                  <FlexItem>
                    <Text component={TextVariants.h4} style={{ margin: 0 }}>{name}</Text>
                  </FlexItem>
                  <FlexItem>
                    <Text component={TextVariants.small} style={{ color: 'var(--pf-v5-global--Color--200)', marginLeft: '8px' }}>
                      {cat.description}
                    </Text>
                  </FlexItem>
                  <FlexItem style={{ marginLeft: 'auto' }}>
                    <Badge isRead>{displayMetrics.length} metrics</Badge>
                    {debouncedSearch && metrics.length > 0 && metrics.length < cat.metrics.length && (
                      <Badge style={{ marginLeft: '6px' }}>{metrics.length} match{metrics.length !== 1 ? 'es' : ''}</Badge>
                    )}
                  </FlexItem>
                </Flex>
              }
              isIndented
              style={{ marginBottom: '8px' }}
            >
              <div style={{ padding: '8px 0' }}>
                {displayMetrics.map(metric => (
                  <div
                    key={metric.key}
                    style={{
                      padding: '8px 12px',
                      marginBottom: '6px',
                      borderLeft: '3px solid var(--pf-v5-global--info-color--100)',
                      backgroundColor: 'var(--pf-v5-global--BackgroundColor--200)',
                      borderRadius: '2px',
                    }}
                  >
                    <Flex alignItems={{ default: 'alignItemsCenter' }} style={{ marginBottom: '4px' }}>
                      <FlexItem>
                        <Text component={TextVariants.small} style={{ fontFamily: 'monospace', fontWeight: 600 }}>
                          {metric.key}
                        </Text>
                      </FlexItem>
                      <FlexItem>
                        <Label isCompact color="blue">{metric.label}</Label>
                      </FlexItem>
                      {metric.unit && (
                        <FlexItem>
                          <Label isCompact color="grey" variant="outline">{metric.unit}</Label>
                        </FlexItem>
                      )}
                    </Flex>
                    {metric.description && (
                      <Text component={TextVariants.small} style={{ color: 'var(--pf-v5-global--Color--200)' }}>
                        {metric.description}
                      </Text>
                    )}
                  </div>
                ))}
              </div>
            </ExpandableSection>
          );
        })
      )}
    </div>
  );
};
