apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.slackWebhook.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{ .Values.slackWebhook.secretKey }}: {{ .Values.slackWebhook.url | default "" | quote }}
