apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default "aiobs-ui" }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8501
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.deployment.name | default "aiobs-ui" }}
