{{- $content := include "llama-stack-instance.configContent" . -}}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "llama-stack-instance.fullname" . }}-config
data:
  config.yaml: |
{{ $content | indent 4 }}
  run.yaml: |
{{ $content | indent 4 }}
