{{- $models := include "llama-stack-instance.mergeModels" . | fromJson }}
---
apiVersion: llamastack.io/v1alpha1
kind: LlamaStackDistribution
metadata:
  name: {{ include "llama-stack-instance.fullname" . }}
  labels:
    {{- include "llama-stack-instance.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas | default 1 }}
  server:
    distribution:
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
    containerSpec:
      name: llama-stack
      port: {{ .Values.service.port }}
      env:
        {{- toYaml .Values.env | nindent 8 }}
        {{- if .Values.otelExporter }}
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: {{ .Values.otelExporter }}
        {{- end }}
        {{- range $key, $value := .Values.secrets }}
        - name: {{ $key }}
          valueFrom:
            secretKeyRef:
              name: {{ include "llama-stack-instance.fullname" $ }}-env
              key: {{ $key }}
        {{- end }}
      {{- with .Values.resources }}
      resources:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    userConfig:
      configMapName: {{ include "llama-stack-instance.fullname" . }}-config
    podOverrides:
      volumeMounts:
        - name: dot-llama
          mountPath: /.llama
        - name: cache
          mountPath: /.cache
      volumes:
        - name: dot-llama
          persistentVolumeClaim:
            claimName: llama-stack-data
        - name: cache
          emptyDir: {}
