kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "llama-stack-instance.dataClaimName" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
