{{- if .Values.secrets }}
{{- if gt (len .Values.secrets) 0 }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "llama-stack-instance.fullname" . }}-env
type: Opaque
data:
  {{- range $key, $value:= .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
